# Generated by Django 3.1.5 on 2021-01-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('notes', '0003_note_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topics.topic'),
            preserve_default=False,
        ),
    ]
